### ISSUE TITLE
Network Shared Media ( You don't have access to any other sites media...) 

### ISSUE THREAD

**Issue by ghost** [joostdekeijzer/wp_network_shared_media#3]
Hi,

I'm receiving this error when I push my site to production.
You don't have access to any other sites media... .

At this URL (http://wordpress.org/support/topic/plugin-network-shared-media-you-dont-have-access-to-any-other-sites-media), it says that I need to have upload_plugin access or needs to be an Editor, but I logged in as an Administrator and still see this error.

I'd be very thankful if you can help me out.

**Comment by migash** [comment]
I resolved this same problem by setting “public” to “1” for each entry in the wp_blogs table in the database

**Comment by jornhenkes** [comment]
Is there a sustainable fix for this already?

**Comment by joostdekeijzer** [comment]
Setting the sites to "Public" is the sustainable fix. See https://wordpress.org/plugins/network-shared-media/#faq
